### ISSUE TITLE
conda-forge build available, but hatchling troubles persist

### ISSUE THREAD

**Issue by akrherz** [a-urq/ecape-parcel-py#3]
Hi @a-urq , I have good news

- ecape-parcel is now on [conda-forge](https://anaconda.org/conda-forge/ecape-parcel) 

The bad news is that I had to gut the hatchling build system to get it to build there.  I have zero experience with hatchling, so I could have been doing something wrong there.  Anyway, this issue is for you to consider adding a documentation blurb about the ability to install this package from there, like what [sounderpy did](https://twitter.com/wxkylegillett/status/1765419870999478610)

**Comment by akrherz** [comment]
[55afbf4](https://github.com/a-urq/ecape-parcel-py/pull/2/commits/55afbf44de2e4edb49680179c9a991987203947d) in #2 hopefully addresses this build issue with latest hatchling

**Comment by a-urq** [comment]
I've added the blurb to the README. Hopefully the build system issues aren't too difficult to work out.
